### ISSUE TITLE
提示INFOError锛宔rrCode=2是啥原因啊

### ISSUE THREAD

**Issue by blassck** [HollowMan6/Srun-LZU-Network-Auth#1]

**Comment by HollowMan6** [comment]
https://github.com/HollowMan6/Srun-LZU-Network-Auth/blob/main/slna.py#L26

设备不在认证区域内

可能是你连的不是校园网？或者单纯的就是校园网卡了，可以等等再试。

**Comment by blassck** [comment]
GitHub上我也看过，无线网络是正常的，接了有线就不行

Hollow Man ***@***.***> 于2021年5月30日周日 上午9:02写道：

**Comment by HollowMan6** [comment]
> GitHub上我也看过，无线网络是正常的，接了有线就不行

你是接了有线的用我的软件这样报错，用学校的登录认证正常，还是什么？如果连学校的登录认证也报错的话，正如我之前所说的，这个错误意味着设备不在认证区域内，我不太清楚具体你的情况，我这也无能为力。

如果是前者，建议用--loginurl 或 -l 参数来指定 login_url，地址为学校的登录认证网站，类似于`http://10.10.0.166`就好了。

**Comment by blassck** [comment]
都可以了，使用专用的客户端才行，谢谢帮助

---XBMU

>
